all: bypass_safe_linking decrypt_safe_linking fastbin_dup fastbin_reverse_into_tcache house_of_botcake house_of_einherjar house_of_mind_fastbin large_bin_attack mmap_overlapping_chunks poison_null_byte tcache_house_of_spirit tcache_poisoning tcache_stashing_unlink_attack unsafe_unlink house_of_lore

bypass_safe_linking:
	gcc -g -o $@ $@.c

decrypt_safe_linking:
	gcc -g -o $@ $@.c

fastbin_dup:
	gcc -g -o $@ $@.c

fastbin_reverse_into_tcache:
	gcc -g -o $@ $@.c

house_of_botcake:
	gcc -g -o $@ $@.c

house_of_einherjar:
	gcc -g -o $@ $@.c

house_of_lore:
	gcc -g -o $@ $@.c

house_of_mind_fastbin:
	gcc -g -o $@ $@.c

large_bin_attack:
	gcc -g -o $@ $@.c

mmap_overlapping_chunks:
	gcc -g -o $@ $@.c

poison_null_byte:
	gcc -g -o $@ $@.c

tcache_house_of_spirit:
	gcc -g -o $@ $@.c

tcache_poisoning:
	gcc -g -o $@ $@.c

tcache_stashing_unlink_attack:
	gcc -g -o $@ $@.c

unsafe_unlink:
	gcc -g -o $@ $@.c

clean:
	rm bypass_safe_linking decrypt_safe_linking fastbin_dup fastbin_reverse_into_tcache house_of_botcake house_of_einherjar house_of_mind_fastbin large_bin_attack mmap_overlapping_chunks poison_null_byte tcache_house_of_spirit tcache_poisoning tcache_stashing_unlink_attack unsafe_unlink