all: demo_double_free demo_fastbin demo_double_free demo_fastbin demo_heap_overflow demo_largebin demo_malloc_state demo_overlapping_chunks demo_smallbin demo_tcache_poisoning demo_tcache demo_UAF demo_unsortedbin

demo_double_free:
	gcc -g -o $@ $@.c

demo_fastbin:
	gcc -g -o $@ $@.c

demo_heap_overflow:
	gcc -g -o $@ $@.c

demo_largebin:
	gcc -g -o $@ $@.c

demo_malloc_state:
	gcc -g -o $@ $@.c

demo_overlapping_chunks:
	gcc -g -o $@ $@.c

demo_smallbin:
	gcc -g -o $@ $@.c

demo_tcache_poisoning:
	gcc -g -o $@ $@.c

demo_tcache:
	gcc -g -o $@ $@.c

demo_UAF:
	gcc -g -o $@ $@.c

demo_unsortedbin:
	gcc -g -o $@ $@.c

